server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;
  location /api/ {
    proxy_pass http://api:3001;
  }
  location / {
    try_files $uri $uri/ /index.html;
  }
}
